from fpdf import FPDF

class PDFReport(FPDF):
    def header(self):
        # Professional Header
        self.set_font('Arial', 'B', 16)
        self.set_text_color(79, 70, 229) # StartNerve Purple
        self.cell(0, 10, 'StartNerve Bio-Engine', 0, 1, 'L')
        self.set_font('Arial', 'I', 10)
        self.set_text_color(100, 100, 100)
        self.cell(0, 5, 'In-Silico Toxicity Certificate of Analysis', 0, 1, 'L')
        self.line(10, 25, 200, 25) # Line break
        self.ln(10)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, f'Page {self.page_no()} | Generated by StartNerve AI (v5.0)', 0, 0, 'C')

def generate_pdf(smiles, mw, logp, predictions, tasks, task_desc, match_name, match_score):
    pdf = PDFReport()
    pdf.add_page()
    
    # 1. COMPOUND DETAILS
    pdf.set_font('Arial', 'B', 12)
    pdf.set_text_color(0, 0, 0)
    pdf.cell(0, 10, '1. Compound Identification', 0, 1)
    
    pdf.set_font('Arial', '', 10)
    pdf.cell(50, 8, 'SMILES Code:', 0, 0)
    pdf.set_font('Courier', '', 9) 
    pdf.multi_cell(0, 8, smiles)
    
    pdf.set_font('Arial', '', 10)
    pdf.cell(50, 8, f'Molecular Weight: {mw:.2f} g/mol', 0, 1)
    pdf.cell(50, 8, f'Lipophilicity (LogP): {logp:.2f}', 0, 1)
    pdf.cell(50, 8, f'FDA Similarity Match: {match_name} ({match_score*100:.1f}%)', 0, 1)
    pdf.ln(5)

    # 2. TOXICITY TABLE
    pdf.set_font('Arial', 'B', 12)
    pdf.cell(0, 10, '2. Tox21 Screening Results', 0, 1)
    
    # Header
    pdf.set_fill_color(240, 240, 240)
    pdf.set_font('Arial', 'B', 10)
    pdf.cell(110, 8, 'Toxicity Endpoint (Target)', 1, 0, 'L', 1)
    pdf.cell(40, 8, 'Prediction', 1, 1, 'C', 1)
    
    # Rows
    pdf.set_font('Arial', '', 10)
    for i, task in enumerate(tasks):
        if task in task_desc:
            label = task_desc[task]
            risk = predictions[i]
            
            pdf.cell(110, 8, label, 1, 0, 'L')
            if risk == 0:
                pdf.set_text_color(0, 150, 0) # Green
                pdf.cell(40, 8, 'SAFE', 1, 1, 'C')
            else:
                pdf.set_text_color(200, 0, 0) # Red
                pdf.cell(40, 8, 'DETECTED', 1, 1, 'C')
            pdf.set_text_color(0, 0, 0) # Reset

    # 3. DISCLAIMER
    pdf.ln(10)
    pdf.set_font('Arial', 'I', 8)
    pdf.set_text_color(100, 100, 100)
    pdf.multi_cell(0, 5, "DISCLAIMER: This report is an AI prediction based on the Tox21 dataset. It is not a clinical diagnosis. Please verify all results with in-vitro assays.")

    return bytes(pdf.output())